---
- name: play for creating new file
  hosts: allservers
  tasks:
   - name: create a file if it does not exist
     file:
      path: /tmp/fileansi.txt
      state: touch
      mode: '0750'


   - name: create a directory if it does not exist
     file:
      path: /tmp/diransi
      state: directory
      mode: '0750'

...

