---
- name: Download Tomcat10 from tomcat.apache.org for webservers
  hosts: webservers
  
  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
       update_cache: yes
    - name: installing java if not present
      become: yes
      apt: 
       name: openjdk-11-jre-headless
       state: present
       update_cache: yes
    - name: Create the user
      become: yes
      user:
       name: tomcat
       state: present
    - name: validate if Java is availble 
      shell: 
       java -version
    - name: Create the group
      become: yes
      group: 
       name: tomcat
       state: present
    - name: Create the user
      become: yes
      user:
       name: tomcat
       state: present
    - name: Create a Directory /opt/tomcat10
      become: yes
      file:
       path: /opt/tomcat10
       state: directory
       mode: 0755
       owner: tomcat
       group: tomcat
    - name: download & unarchive tomcat10 
      unarchive:
       src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz
       dest: /opt/tomcat10
       remote_src: yes
       extra_opts: [--strip-components=1]
       
    
    
    - name: Creating a service file
      become: yes
      copy: 
       content: |-
        [Unit]
        Description=Tomcat
        After=network.target
        [Service]
        Type=forking
        User=tomcat
        Group=tomcat
        Environment="JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64"
        Environment="JAVA_OPTS=-Djava.security.egd=file:///dev/urandom"
        Environment="CATALINA_BASE=/opt/tomcat"
        Environment="CATALINA_HOME=/opt/tomcat"
        Environment="CATALINA_PID=/opt/tomcat/temp/tomcat.pid"
        Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
        ExecStart=/opt/tomcat/bin/startup.sh
        ExecStop=/opt/tomcat/bin/shutdown.sh
        RestartSec=10
        Restart=always
        [Install]
        WantedBy=multi-user.target
       dest: /etc/systemd/system/tomcat.service
    - name: Reload the SystemD to re-read configurations
      become: yes
      systemd:
       daemon-reload: yes
    
    - name: Enable the tomcat service and start
      become: yes
      systemd:
       name: tomcat
       enabled: yes
       state: started
    - name: Start and Enable Tomcat 10 on sever
      systemd:
       name: tomcat
       state: started
       daemon_reload: true

    - name: Connect to Tomcat server on port 8080 
      tags: test
      uri:
       url: http://localhost:8080
      register: result
      
     
      